# Generated by Django 4.1.2 on 2022-10-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='happiness',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
