# Generated by Django 4.1.2 on 2022-10-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_happiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='happiness',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
